# Generated by Django 4.2.5 on 2023-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
    #     migrations.AddField(
    #         model_name='requests',
    #         name='name',
    #         field=models.CharField(max_length=255, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='users',
    #         name='role',
    #         field=models.CharField(max_length=255, null=True),
    #     ),
        migrations.AlterField(
            model_name='employees',
            name='info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='formation_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
