# Generated by Django 4.2.5 on 2023-09-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_requests_name_users_role_alter_employees_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_employees',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='baseapp.employees'),
        ),
        migrations.AlterField(
            model_name='request_employees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request_employees',
            name='request',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='baseapp.requests'),
        ),
    ]
