# Generated by Django 4.2.5 on 2023-09-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_requests_name_users_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_employees',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.employees'),
        ),
        migrations.AlterField(
            model_name='request_employees',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.requests'),
        ),
        migrations.AddConstraint(
            model_name='request_employees',
            constraint=models.UniqueConstraint(fields=('request', 'employee'), name='unique_request_employee'),
        ),
    ]
