# Generated by Django 4.2.5 on 2023-09-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('entered', 'Entered'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('deleted', 'Deleted')], max_length=20)),
                ('created_date', models.DateField()),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_requests', to='baseapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='request_employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.employees')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.requests')),
            ],
        ),
    ]
