# Generated by Django 4.2.5 on 2023-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_employees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
