# Generated by Django 4.2.4 on 2023-10-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/')),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('entered', 'Entered'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('deleted', 'Deleted')], max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('formation_date', models.DateField(auto_now=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_requests', to='stocks.users')),
            ],
            options={
                'verbose_name_plural': 'Requests',
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Request_Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.employees')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.requests')),
            ],
            options={
                'verbose_name_plural': 'Request Employees',
                'db_table': 'request_employees',
            },
        ),
        migrations.AddConstraint(
            model_name='request_employees',
            constraint=models.UniqueConstraint(fields=('request', 'employee'), name='unique_request_employee'),
        ),
    ]
