# Generated by Django 4.2.4 on 2023-10-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_requests_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='formation_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
