# Generated by Django 4.2.4 on 2023-10-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_requests_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='photo_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
