# Generated by Django 4.2.4 on 2023-12-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_employees_photo_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_employees',
            name='security',
            field=models.BooleanField(default=True),
        ),
    ]
