# Generated by Django 4.2.4 on 2023-12-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_request_employees_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_employees',
            name='security',
            field=models.BooleanField(null=True),
        ),
    ]
