# Generated by Django 4.2.4 on 2024-01-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_requests_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='stocks.users'),
        ),
    ]
