# Generated by Django 4.2.4 on 2024-01-31 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_requests_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_requests', to='stocks.users'),
        ),
    ]
